// mksyscall.pl -l32 api_linux.go
// MACHINE GENERATED BY THE COMMAND ABOVE; DO NOT EDIT

package api

import "syscall"

// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func ioctl(fd uintptr, action uintptr, arg uintptr) (err error) {
	_, _, e1 := syscall.Syscall(syscall.SYS_IOCTL, uintptr(fd), uintptr(action), uintptr(arg))
	if e1 != 0 {
		err = e1
	}
	return
}
