// mksyscall.pl -l32 -tags linux,386 api_linux.go
// Code generated by the command above; DO NOT EDIT.

package api

import "syscall"

// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func ioctl(fd uintptr, action uintptr, arg uintptr) (err error) {
	_, _, e1 := syscall.Syscall(syscall.SYS_IOCTL, uintptr(fd), uintptr(action), uintptr(arg))
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
