// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs types.go

package linux

type CanFrame struct {
	Id      uint32
	Dlc     uint8
	X__pad  uint8
	X__res0 uint8
	X__res1 uint8
	Data    [8]uint8
}
type CanfdFrame struct {
	Id      uint32
	Len     uint8
	Flags   uint8
	X__res0 uint8
	X__res1 uint8
	Data    [64]uint8
}
